name: Run Deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4
      - name: Установка зависимостей
        run: npm install
      - name: Запуск тестов
        run: npm run test:ci
      - name: Запуск eslint
        run: npm run lint
      - name: Запуск build
        run: npm run build
  