name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4
      - name: Установка зависимостей
        run: npm install
      - name: Запуск тестов
        run: npm run test:ci


